# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/work/pdj/supports/blive-api-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/work/pdj/supports/blive-api-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/work/pdj/supports/blive-api-c/CMakeFiles /mnt/e/work/pdj/supports/blive-api-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/work/pdj/supports/blive-api-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cjson_s

# Build rule for target.
cjson_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cjson_s
.PHONY : cjson_s

# fast build rule for target.
cjson_s/fast:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/build
.PHONY : cjson_s/fast

#=============================================================================
# Target rules for targets named cjson

# Build rule for target.
cjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cjson
.PHONY : cjson

# fast build rule for target.
cjson/fast:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/build
.PHONY : cjson/fast

#=============================================================================
# Target rules for targets named brotli_s

# Build rule for target.
brotli_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brotli_s
.PHONY : brotli_s

# fast build rule for target.
brotli_s/fast:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/build
.PHONY : brotli_s/fast

#=============================================================================
# Target rules for targets named brotli

# Build rule for target.
brotli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brotli
.PHONY : brotli

# fast build rule for target.
brotli/fast:
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/build
.PHONY : brotli/fast

#=============================================================================
# Target rules for targets named blive_api_s

# Build rule for target.
blive_api_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blive_api_s
.PHONY : blive_api_s

# fast build rule for target.
blive_api_s/fast:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/build
.PHONY : blive_api_s/fast

#=============================================================================
# Target rules for targets named blive_api

# Build rule for target.
blive_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blive_api
.PHONY : blive_api

# fast build rule for target.
blive_api/fast:
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/build
.PHONY : blive_api/fast

external_supports/brotli/common/constants.o: external_supports/brotli/common/constants.c.o

.PHONY : external_supports/brotli/common/constants.o

# target to build an object file
external_supports/brotli/common/constants.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/constants.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/constants.c.o
.PHONY : external_supports/brotli/common/constants.c.o

external_supports/brotli/common/constants.i: external_supports/brotli/common/constants.c.i

.PHONY : external_supports/brotli/common/constants.i

# target to preprocess a source file
external_supports/brotli/common/constants.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/constants.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/constants.c.i
.PHONY : external_supports/brotli/common/constants.c.i

external_supports/brotli/common/constants.s: external_supports/brotli/common/constants.c.s

.PHONY : external_supports/brotli/common/constants.s

# target to generate assembly for a file
external_supports/brotli/common/constants.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/constants.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/constants.c.s
.PHONY : external_supports/brotli/common/constants.c.s

external_supports/brotli/common/context.o: external_supports/brotli/common/context.c.o

.PHONY : external_supports/brotli/common/context.o

# target to build an object file
external_supports/brotli/common/context.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/context.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/context.c.o
.PHONY : external_supports/brotli/common/context.c.o

external_supports/brotli/common/context.i: external_supports/brotli/common/context.c.i

.PHONY : external_supports/brotli/common/context.i

# target to preprocess a source file
external_supports/brotli/common/context.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/context.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/context.c.i
.PHONY : external_supports/brotli/common/context.c.i

external_supports/brotli/common/context.s: external_supports/brotli/common/context.c.s

.PHONY : external_supports/brotli/common/context.s

# target to generate assembly for a file
external_supports/brotli/common/context.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/context.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/context.c.s
.PHONY : external_supports/brotli/common/context.c.s

external_supports/brotli/common/dictionary.o: external_supports/brotli/common/dictionary.c.o

.PHONY : external_supports/brotli/common/dictionary.o

# target to build an object file
external_supports/brotli/common/dictionary.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/dictionary.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/dictionary.c.o
.PHONY : external_supports/brotli/common/dictionary.c.o

external_supports/brotli/common/dictionary.i: external_supports/brotli/common/dictionary.c.i

.PHONY : external_supports/brotli/common/dictionary.i

# target to preprocess a source file
external_supports/brotli/common/dictionary.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/dictionary.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/dictionary.c.i
.PHONY : external_supports/brotli/common/dictionary.c.i

external_supports/brotli/common/dictionary.s: external_supports/brotli/common/dictionary.c.s

.PHONY : external_supports/brotli/common/dictionary.s

# target to generate assembly for a file
external_supports/brotli/common/dictionary.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/dictionary.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/dictionary.c.s
.PHONY : external_supports/brotli/common/dictionary.c.s

external_supports/brotli/common/platform.o: external_supports/brotli/common/platform.c.o

.PHONY : external_supports/brotli/common/platform.o

# target to build an object file
external_supports/brotli/common/platform.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/platform.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/platform.c.o
.PHONY : external_supports/brotli/common/platform.c.o

external_supports/brotli/common/platform.i: external_supports/brotli/common/platform.c.i

.PHONY : external_supports/brotli/common/platform.i

# target to preprocess a source file
external_supports/brotli/common/platform.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/platform.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/platform.c.i
.PHONY : external_supports/brotli/common/platform.c.i

external_supports/brotli/common/platform.s: external_supports/brotli/common/platform.c.s

.PHONY : external_supports/brotli/common/platform.s

# target to generate assembly for a file
external_supports/brotli/common/platform.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/platform.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/platform.c.s
.PHONY : external_supports/brotli/common/platform.c.s

external_supports/brotli/common/shared_dictionary.o: external_supports/brotli/common/shared_dictionary.c.o

.PHONY : external_supports/brotli/common/shared_dictionary.o

# target to build an object file
external_supports/brotli/common/shared_dictionary.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/shared_dictionary.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/shared_dictionary.c.o
.PHONY : external_supports/brotli/common/shared_dictionary.c.o

external_supports/brotli/common/shared_dictionary.i: external_supports/brotli/common/shared_dictionary.c.i

.PHONY : external_supports/brotli/common/shared_dictionary.i

# target to preprocess a source file
external_supports/brotli/common/shared_dictionary.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/shared_dictionary.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/shared_dictionary.c.i
.PHONY : external_supports/brotli/common/shared_dictionary.c.i

external_supports/brotli/common/shared_dictionary.s: external_supports/brotli/common/shared_dictionary.c.s

.PHONY : external_supports/brotli/common/shared_dictionary.s

# target to generate assembly for a file
external_supports/brotli/common/shared_dictionary.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/shared_dictionary.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/shared_dictionary.c.s
.PHONY : external_supports/brotli/common/shared_dictionary.c.s

external_supports/brotli/common/transform.o: external_supports/brotli/common/transform.c.o

.PHONY : external_supports/brotli/common/transform.o

# target to build an object file
external_supports/brotli/common/transform.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/transform.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/transform.c.o
.PHONY : external_supports/brotli/common/transform.c.o

external_supports/brotli/common/transform.i: external_supports/brotli/common/transform.c.i

.PHONY : external_supports/brotli/common/transform.i

# target to preprocess a source file
external_supports/brotli/common/transform.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/transform.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/transform.c.i
.PHONY : external_supports/brotli/common/transform.c.i

external_supports/brotli/common/transform.s: external_supports/brotli/common/transform.c.s

.PHONY : external_supports/brotli/common/transform.s

# target to generate assembly for a file
external_supports/brotli/common/transform.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/common/transform.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/common/transform.c.s
.PHONY : external_supports/brotli/common/transform.c.s

external_supports/brotli/dec/bit_reader.o: external_supports/brotli/dec/bit_reader.c.o

.PHONY : external_supports/brotli/dec/bit_reader.o

# target to build an object file
external_supports/brotli/dec/bit_reader.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/bit_reader.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/bit_reader.c.o
.PHONY : external_supports/brotli/dec/bit_reader.c.o

external_supports/brotli/dec/bit_reader.i: external_supports/brotli/dec/bit_reader.c.i

.PHONY : external_supports/brotli/dec/bit_reader.i

# target to preprocess a source file
external_supports/brotli/dec/bit_reader.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/bit_reader.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/bit_reader.c.i
.PHONY : external_supports/brotli/dec/bit_reader.c.i

external_supports/brotli/dec/bit_reader.s: external_supports/brotli/dec/bit_reader.c.s

.PHONY : external_supports/brotli/dec/bit_reader.s

# target to generate assembly for a file
external_supports/brotli/dec/bit_reader.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/bit_reader.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/bit_reader.c.s
.PHONY : external_supports/brotli/dec/bit_reader.c.s

external_supports/brotli/dec/decode.o: external_supports/brotli/dec/decode.c.o

.PHONY : external_supports/brotli/dec/decode.o

# target to build an object file
external_supports/brotli/dec/decode.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/decode.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/decode.c.o
.PHONY : external_supports/brotli/dec/decode.c.o

external_supports/brotli/dec/decode.i: external_supports/brotli/dec/decode.c.i

.PHONY : external_supports/brotli/dec/decode.i

# target to preprocess a source file
external_supports/brotli/dec/decode.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/decode.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/decode.c.i
.PHONY : external_supports/brotli/dec/decode.c.i

external_supports/brotli/dec/decode.s: external_supports/brotli/dec/decode.c.s

.PHONY : external_supports/brotli/dec/decode.s

# target to generate assembly for a file
external_supports/brotli/dec/decode.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/decode.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/decode.c.s
.PHONY : external_supports/brotli/dec/decode.c.s

external_supports/brotli/dec/huffman.o: external_supports/brotli/dec/huffman.c.o

.PHONY : external_supports/brotli/dec/huffman.o

# target to build an object file
external_supports/brotli/dec/huffman.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/huffman.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/huffman.c.o
.PHONY : external_supports/brotli/dec/huffman.c.o

external_supports/brotli/dec/huffman.i: external_supports/brotli/dec/huffman.c.i

.PHONY : external_supports/brotli/dec/huffman.i

# target to preprocess a source file
external_supports/brotli/dec/huffman.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/huffman.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/huffman.c.i
.PHONY : external_supports/brotli/dec/huffman.c.i

external_supports/brotli/dec/huffman.s: external_supports/brotli/dec/huffman.c.s

.PHONY : external_supports/brotli/dec/huffman.s

# target to generate assembly for a file
external_supports/brotli/dec/huffman.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/huffman.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/huffman.c.s
.PHONY : external_supports/brotli/dec/huffman.c.s

external_supports/brotli/dec/state.o: external_supports/brotli/dec/state.c.o

.PHONY : external_supports/brotli/dec/state.o

# target to build an object file
external_supports/brotli/dec/state.c.o:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/state.c.o
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/state.c.o
.PHONY : external_supports/brotli/dec/state.c.o

external_supports/brotli/dec/state.i: external_supports/brotli/dec/state.c.i

.PHONY : external_supports/brotli/dec/state.i

# target to preprocess a source file
external_supports/brotli/dec/state.c.i:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/state.c.i
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/state.c.i
.PHONY : external_supports/brotli/dec/state.c.i

external_supports/brotli/dec/state.s: external_supports/brotli/dec/state.c.s

.PHONY : external_supports/brotli/dec/state.s

# target to generate assembly for a file
external_supports/brotli/dec/state.c.s:
	$(MAKE) -f CMakeFiles/brotli_s.dir/build.make CMakeFiles/brotli_s.dir/external_supports/brotli/dec/state.c.s
	$(MAKE) -f CMakeFiles/brotli.dir/build.make CMakeFiles/brotli.dir/external_supports/brotli/dec/state.c.s
.PHONY : external_supports/brotli/dec/state.c.s

external_supports/cJSON/cJSON.o: external_supports/cJSON/cJSON.c.o

.PHONY : external_supports/cJSON/cJSON.o

# target to build an object file
external_supports/cJSON/cJSON.c.o:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON.c.o
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON.c.o
.PHONY : external_supports/cJSON/cJSON.c.o

external_supports/cJSON/cJSON.i: external_supports/cJSON/cJSON.c.i

.PHONY : external_supports/cJSON/cJSON.i

# target to preprocess a source file
external_supports/cJSON/cJSON.c.i:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON.c.i
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON.c.i
.PHONY : external_supports/cJSON/cJSON.c.i

external_supports/cJSON/cJSON.s: external_supports/cJSON/cJSON.c.s

.PHONY : external_supports/cJSON/cJSON.s

# target to generate assembly for a file
external_supports/cJSON/cJSON.c.s:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON.c.s
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON.c.s
.PHONY : external_supports/cJSON/cJSON.c.s

external_supports/cJSON/cJSON_Utils.o: external_supports/cJSON/cJSON_Utils.c.o

.PHONY : external_supports/cJSON/cJSON_Utils.o

# target to build an object file
external_supports/cJSON/cJSON_Utils.c.o:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON_Utils.c.o
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON_Utils.c.o
.PHONY : external_supports/cJSON/cJSON_Utils.c.o

external_supports/cJSON/cJSON_Utils.i: external_supports/cJSON/cJSON_Utils.c.i

.PHONY : external_supports/cJSON/cJSON_Utils.i

# target to preprocess a source file
external_supports/cJSON/cJSON_Utils.c.i:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON_Utils.c.i
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON_Utils.c.i
.PHONY : external_supports/cJSON/cJSON_Utils.c.i

external_supports/cJSON/cJSON_Utils.s: external_supports/cJSON/cJSON_Utils.c.s

.PHONY : external_supports/cJSON/cJSON_Utils.s

# target to generate assembly for a file
external_supports/cJSON/cJSON_Utils.c.s:
	$(MAKE) -f CMakeFiles/cjson_s.dir/build.make CMakeFiles/cjson_s.dir/external_supports/cJSON/cJSON_Utils.c.s
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/external_supports/cJSON/cJSON_Utils.c.s
.PHONY : external_supports/cJSON/cJSON_Utils.c.s

source/blive.o: source/blive.c.o

.PHONY : source/blive.o

# target to build an object file
source/blive.c.o:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/blive.c.o
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/blive.c.o
.PHONY : source/blive.c.o

source/blive.i: source/blive.c.i

.PHONY : source/blive.i

# target to preprocess a source file
source/blive.c.i:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/blive.c.i
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/blive.c.i
.PHONY : source/blive.c.i

source/blive.s: source/blive.c.s

.PHONY : source/blive.s

# target to generate assembly for a file
source/blive.c.s:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/blive.c.s
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/blive.c.s
.PHONY : source/blive.c.s

source/conn.o: source/conn.c.o

.PHONY : source/conn.o

# target to build an object file
source/conn.c.o:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/conn.c.o
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/conn.c.o
.PHONY : source/conn.c.o

source/conn.i: source/conn.c.i

.PHONY : source/conn.i

# target to preprocess a source file
source/conn.c.i:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/conn.c.i
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/conn.c.i
.PHONY : source/conn.c.i

source/conn.s: source/conn.c.s

.PHONY : source/conn.s

# target to generate assembly for a file
source/conn.c.s:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/conn.c.s
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/conn.c.s
.PHONY : source/conn.c.s

source/log.o: source/log.c.o

.PHONY : source/log.o

# target to build an object file
source/log.c.o:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/log.c.o
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/log.c.o
.PHONY : source/log.c.o

source/log.i: source/log.c.i

.PHONY : source/log.i

# target to preprocess a source file
source/log.c.i:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/log.c.i
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/log.c.i
.PHONY : source/log.c.i

source/log.s: source/log.c.s

.PHONY : source/log.s

# target to generate assembly for a file
source/log.c.s:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/log.c.s
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/log.c.s
.PHONY : source/log.c.s

source/msg.o: source/msg.c.o

.PHONY : source/msg.o

# target to build an object file
source/msg.c.o:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/msg.c.o
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/msg.c.o
.PHONY : source/msg.c.o

source/msg.i: source/msg.c.i

.PHONY : source/msg.i

# target to preprocess a source file
source/msg.c.i:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/msg.c.i
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/msg.c.i
.PHONY : source/msg.c.i

source/msg.s: source/msg.c.s

.PHONY : source/msg.s

# target to generate assembly for a file
source/msg.c.s:
	$(MAKE) -f CMakeFiles/blive_api_s.dir/build.make CMakeFiles/blive_api_s.dir/source/msg.c.s
	$(MAKE) -f CMakeFiles/blive_api.dir/build.make CMakeFiles/blive_api.dir/source/msg.c.s
.PHONY : source/msg.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... cjson_s"
	@echo "... rebuild_cache"
	@echo "... cjson"
	@echo "... brotli_s"
	@echo "... brotli"
	@echo "... blive_api_s"
	@echo "... blive_api"
	@echo "... external_supports/brotli/common/constants.o"
	@echo "... external_supports/brotli/common/constants.i"
	@echo "... external_supports/brotli/common/constants.s"
	@echo "... external_supports/brotli/common/context.o"
	@echo "... external_supports/brotli/common/context.i"
	@echo "... external_supports/brotli/common/context.s"
	@echo "... external_supports/brotli/common/dictionary.o"
	@echo "... external_supports/brotli/common/dictionary.i"
	@echo "... external_supports/brotli/common/dictionary.s"
	@echo "... external_supports/brotli/common/platform.o"
	@echo "... external_supports/brotli/common/platform.i"
	@echo "... external_supports/brotli/common/platform.s"
	@echo "... external_supports/brotli/common/shared_dictionary.o"
	@echo "... external_supports/brotli/common/shared_dictionary.i"
	@echo "... external_supports/brotli/common/shared_dictionary.s"
	@echo "... external_supports/brotli/common/transform.o"
	@echo "... external_supports/brotli/common/transform.i"
	@echo "... external_supports/brotli/common/transform.s"
	@echo "... external_supports/brotli/dec/bit_reader.o"
	@echo "... external_supports/brotli/dec/bit_reader.i"
	@echo "... external_supports/brotli/dec/bit_reader.s"
	@echo "... external_supports/brotli/dec/decode.o"
	@echo "... external_supports/brotli/dec/decode.i"
	@echo "... external_supports/brotli/dec/decode.s"
	@echo "... external_supports/brotli/dec/huffman.o"
	@echo "... external_supports/brotli/dec/huffman.i"
	@echo "... external_supports/brotli/dec/huffman.s"
	@echo "... external_supports/brotli/dec/state.o"
	@echo "... external_supports/brotli/dec/state.i"
	@echo "... external_supports/brotli/dec/state.s"
	@echo "... external_supports/cJSON/cJSON.o"
	@echo "... external_supports/cJSON/cJSON.i"
	@echo "... external_supports/cJSON/cJSON.s"
	@echo "... external_supports/cJSON/cJSON_Utils.o"
	@echo "... external_supports/cJSON/cJSON_Utils.i"
	@echo "... external_supports/cJSON/cJSON_Utils.s"
	@echo "... source/blive.o"
	@echo "... source/blive.i"
	@echo "... source/blive.s"
	@echo "... source/conn.o"
	@echo "... source/conn.i"
	@echo "... source/conn.s"
	@echo "... source/log.o"
	@echo "... source/log.i"
	@echo "... source/log.s"
	@echo "... source/msg.o"
	@echo "... source/msg.i"
	@echo "... source/msg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

